services:
  flask-app:
    container_name: flask-app
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgres://elsjbyqx:thpxz1QRoIbx34LqqsgLsAG3kdxCcfGg@lallah.db.elephantsql.com/elsjbyqx
